#!/bin/bash

##########################################################################
#
#  Script:    prep_spm_dcm.pbs
#  Author:    Sebastien Naze
#  Created:   2022-02
#
##########################################################################

#PBS -N prep_spm_dcm
#PBS -l ncpus=2,mem=24gb,walltime=00:45:00
#PBS -m abe
#PBS -M sebastien.naze@qimrberghofer.edu.au
#PBS -o /working/lab_lucac/sebastiN/projects/OCDbaseline/.pbs_logs/
#PBS -e /working/lab_lucac/sebastiN/projects/OCDbaseline/.pbs_logs/
#
# Script to prepare individual subjects files to perform DCM
#

module load fsl/6.0.1
module load miniconda3/current

source activate /mnt/lustre/working/lab_lucac/lukeH/ljh-neuro

proj_dir=/mnt/lustre/working/lab_lucac/sebastiN/projects/OCDbaseline/
lukeH_proj_dir=/mnt/lustre/working/lab_lucac/lukeH/projects/OCDbaseline/
pp_dir=${proj_dir}postprocessing/

# load specific subject from subject list
mapfile -t subj_array < ${proj_dir}docs/code/subject_list.txt
IDX=$((PBS_ARRAY_INDEX-1))  # double parenthesis needed for arithmetic operations
subj=${subj_array[$IDX]}
echo "Current subject: " ${subj}

echo 'Denoising '${subj}
python ${proj_dir}docs/code/preprocessing/post_fmriprep_denoising.py ${subj}

#echo 'Preparing for SPM '${subj}
#mkdir -p ${pp_dir}${subj}/spm/scans/detrend_gsr_smooth6mm/
#fslsplit ${proj_dir}data/derivatives/post-fmriprep-fix/${subj}/func/${subj}_task-rest_space-MNI152NLin2009cAsym_desc-detrend_gsr_smooth-6mm.nii.gz  ${pp_dir}${subj}/spm/scans/detrend_gsr_smooth6mm/${subj}_task-rest_space-MNI152NLin2009cAsym_desc-detrend_gsr_smooth-6mm
#gzip -d ${pp_dir}${subj}/spm/scans/detrend_gsr_smooth6mm/*

#mkdir -p ${pp_dir}${subj}/spm/scans/
#fslsplit ${lukeH_proj_dir}data/derivatives/post-fmriprep-fix/${subj}/func/${subj}_task-rest_space-MNI152NLin2009cAsym_desc-detrend_filtered_gsr_smooth-6mm.nii.gz  ${pp_dir}${subj}/spm/scans/${subj}_task-rest_space-MNI152NLin2009cAsym_desc-detrend_filtered_gsr_smooth-6mm
#gzip -d ${pp_dir}${subj}/spm/scans/*
